const KEY='centralEstudos_v4';
const DEFAULT={answers:{},attempts:[],examHistory:[],xp:0,streak:0,lastDay:null,dark:false,cargo:'Agente Comunitário de Saúde',dailyGoal:20,studyPlan:{},flashSeen:{},srs:{}};
const fresh=()=>({...DEFAULT,answers:{},attempts:[],examHistory:[],studyPlan:{},flashSeen:{},srs:{}});
const SRS_DAYS=[1,3,7,14];
let lastResult=null,state=loadState(),currentPage='dashboard',quiz=null,timer=null;
const $=s=>document.querySelector(s);
const QMAP=new Map(QUESTIONS.map(q=>[q.id,q]));
function rng(seed){let t=seed+0x6D2B79F5;return()=>{t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function perm(q){if(q._p)return q._p;const p=q.a.map((_,i)=>i);if(!q.a.some(x=>/anteriores|nenhuma d|todas as|ambas|^(I|II)\b/i.test(x))){const r=rng(q.id*9973+7);for(let i=p.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[p[i],p[j]]=[p[j],p[i]]}}return q._p=p}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function toast(m){let t=$('#toast');if(!t){t=document.createElement('div');t.id='toast';document.body.appendChild(t)}t.textContent=m;t.classList.add('show');clearTimeout(t._h);t._h=setTimeout(()=>t.classList.remove('show'),2500)}
function localDay(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function dayOf(iso){return iso?localDay(new Date(iso)):''}
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function loadState(){
  try{
    const old=JSON.parse(localStorage.getItem(KEY)||'null');
    if(old)return migrateSrs({...DEFAULT,...old,answers:old.answers||{},attempts:old.attempts||[],examHistory:old.examHistory||[],studyPlan:old.studyPlan||{},flashSeen:old.flashSeen||{},srs:old.srs||{}});
    const v2=JSON.parse(localStorage.getItem('centralEstudos_v2')||'null');
    if(v2)return {...fresh(),...v2,answers:{},attempts:[],examHistory:[]};
  }catch(e){}
  return fresh();
}
function addDays(n){const d=new Date();d.setDate(d.getDate()+n);return localDay(d)}
function migrateSrs(s){Object.entries(s.answers||{}).forEach(([id,r])=>{if(r&&!r.correct&&!s.srs[id])s.srs[id]={box:0,due:localDay(new Date())}});return s}
function dueList(){const t=today();return Object.entries(state.srs).filter(([id,v])=>v.due<=t&&QMAP.has(+id)).sort((a,b)=>a[1].due.localeCompare(b[1].due)).map(e=>+e[0])}
function srsCard(){const n=dueList().length;return `<div class="card" style="margin:15px 0"><h3>🔁 Revisão espaçada</h3><p>${n?`<b>${n}</b> questão(ões) para rever hoje. Erros voltam em 1, 3, 7 e 14 dias.`:'Nada para rever hoje. Questões erradas voltam automaticamente em 1, 3, 7 e 14 dias.'}</p>${n?'<button class="action" onclick="startSrs()">Rever agora</button>':''}</div>`}
function startSrs(){const ids=dueList().slice(0,20);if(!ids.length)return toast('Nada para rever hoje.');quiz={ids,idx:0,mode:'study'};showQuestion()}
function today(){return localDay(new Date())}
function dayCheck(){
  const d=today();
  if(state.lastDay!==d){
    if(state.lastDay){const diff=Math.round((new Date(d+'T00:00')-new Date(state.lastDay+'T00:00'))/86400000);state.streak=diff===1?state.streak+1:1}else state.streak=1;
    state.lastDay=d;save();
  }
  const el=$('#streak');if(el)el.textContent=state.streak;
}
function stats(){const vals=Object.entries(state.answers).filter(e=>QMAP.has(+e[0])).map(e=>e[1]),total=vals.length,correct=vals.filter(x=>x.correct).length;return{total,correct,pct:total?Math.round(correct/total*100):0}}
function subjectStats(subject){const qs=QUESTIONS.filter(q=>q.subject===subject),a=qs.filter(q=>state.answers[q.id]),c=a.filter(q=>q.correct);return{total:qs.length,answered:a.length,correct:c.length,pct:a.length?Math.round(c.length/a.length*100):0}}
function topicStats(){
 const map={};
 QUESTIONS.forEach(q=>{const a=state.answers[q.id];if(!a)return;const k=q.subject+'|'+q.topic;if(!map[k])map[k]={subject:q.subject,topic:q.topic,total:0,wrong:0,correct:0};map[k].total++;a.correct?map[k].correct++:map[k].wrong++});
 return Object.values(map).map(x=>({...x,pct:Math.round(x.correct/x.total*100),errorRate:Math.round(x.wrong/x.total*100)}));
}
function weakTopics(limit=8){return topicStats().filter(x=>x.wrong>0).sort((a,b)=>b.errorRate-a.errorRate||a.pct-b.pct).slice(0,limit)}
function icon(s){return {'Português':'📝','Matemática':'🔢','Agente Comunitário de Saúde':'🩺','Orientador Social':'🤝'}[s]||'📚'}
function render(){
 dayCheck();document.body.classList.toggle('dark',state.dark);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===currentPage));
 const titles={dashboard:'Dashboard',estudar:'Estudar',aulas:'Aulas e conteúdo',plano:'Plano de estudo',simulado:'Simulados',edital:'Meu Edital',revisao:'Revisão inteligente',estatisticas:'Desempenho',ranking:'Meu ranking'};
 $('#pageTitle').textContent=titles[currentPage]||'Dashboard';
 const fn={dashboard,estudar,aulas,plano,simulado,edital,review,statistics,ranking}[currentPage==='revisao'?'review':currentPage]||dashboard;fn();
}
function dashboard(){
 const s=stats(),cargo=state.cargo,todayCount=Object.values(state.answers).filter(x=>dayOf(x.at)===today()).length,weak=weakTopics(5),best=state.examHistory.length?Math.max(...state.examHistory.map(x=>x.pct)):0;
 $('#content').innerHTML=`<div class="wrap">
 <div class="hero"><div><span class="badge">EDITAL PERSONALIZADO • ${QUESTIONS.length} QUESTÕES</span><h2>Seu treino está pronto. 🎯</h2><p>Foco atual: <b>${cargo}</b>. O sistema mede erros por assunto e monta revisões automaticamente.</p></div><button class="action" onclick="go('simulado')">Fazer prova</button></div>
 <div class="grid"><div class="card"><div class="muted">Questões respondidas</div><div class="stat">${s.total}</div></div><div class="card"><div class="muted">Acertos</div><div class="stat">${s.correct}</div></div><div class="card"><div class="muted">Aproveitamento</div><div class="stat">${s.pct}%</div></div><div class="card"><div class="muted">Melhor prova</div><div class="stat">${best||0}%</div></div></div>
 <div class="grid two"><div class="card"><h3>🎯 Meta diária</h3><div class="stat smallstat">${Math.min(todayCount,state.dailyGoal)} / ${state.dailyGoal}</div><div class="progress"><i style="width:${Math.min(100,todayCount/state.dailyGoal*100)}%"></i></div><button class="secondary" onclick="setGoal()">Alterar meta</button></div><div class="card"><h3>⚡ Nível ${level()}</h3><p>${state.xp} XP • ${xpToNext()} XP para o próximo nível</p><div class="progress"><i style="width:${levelPct()}%"></i></div><button class="secondary" onclick="go('ranking')">Ver meu ranking</button></div></div>
 ${srsCard()}<h2>🔎 Revisão recomendada</h2><div class="cards">${weak.length?weak.map(w=>`<div class="card"><span class="badge">${w.subject}</span><h3>${w.topic}</h3><p>${w.wrong} erro(s) em ${w.total} tentativa(s) • <b>${w.errorRate}% de erros</b></p><button class="secondary" onclick="startTopic('${escapeAttr(w.subject)}','${escapeAttr(w.topic)}')">Revisar assunto</button></div>`).join(''):'<div class="card empty">Comece a responder questões para o sistema identificar seus pontos fracos.</div>'}</div>
 <h2>📚 Seu cargo</h2><div class="card"><select id="cargoDash" onchange="changeCargo(this.value)">${Object.keys(EDITAL).filter(x=>x==='Agente Comunitário de Saúde'||x==='Orientador Social').map(c=>`<option ${c===cargo?'selected':''}>${c}</option>`).join('')}</select><p class="muted">${QUESTIONS.filter(q=>q.subject===cargo).length} questões específicas disponíveis.</p></div>
 </div>`;
}
function escapeAttr(s){return String(s).replaceAll('&','&amp;').replaceAll("'",'&#39;').replaceAll('"','&quot;')}
function level(){return Math.floor(state.xp/100)+1}
function xpToNext(){return 100-(state.xp%100)}
function levelPct(){return state.xp%100}
function changeCargo(c){state.cargo=c;save();render()}
function setGoal(){const n=prompt('Meta diária de questões:',state.dailyGoal);const v=Number(n);if(v>=5&&v<=100){state.dailyGoal=v;save();render()}}
function subjects(){return ['Português','Matemática','Agente Comunitário de Saúde','Orientador Social']}
function estudar(){
 $('#content').innerHTML=`<div class="wrap"><div class="toolbar"><select id="studySubject"><option value="">Todas as matérias</option>${subjects().map(x=>`<option>${x}</option>`).join('')}</select><select id="studyTopic"><option value="">Todos os tópicos</option></select><select id="studyDiff"><option value="">Todas as dificuldades</option><option>Fácil</option><option>Médio</option><option>Difícil</option></select><button class="action" onclick="startStudy()">Começar treino</button></div><div class="card"><h3>🧠 Treino adaptativo</h3><p>Questões ainda não respondidas vêm primeiro. Assuntos com maior taxa de erro também recebem prioridade.</p></div><div id="studyList" class="cards" style="margin-top:15px"></div></div>`;
 const sub=$('#studySubject');sub.onchange=()=>{const s=sub.value;$('#studyTopic').innerHTML='<option value="">Todos os tópicos</option>'+(s?(EDITAL[s]||[]).map(t=>`<option>${t}</option>`).join(''):'')};
 renderStudyList();
}
function renderStudyList(){const sub=$('#studySubject')?.value||'',diff=$('#studyDiff')?.value||'';let qs=QUESTIONS.filter(q=>(!sub||q.subject===sub)&&(!diff||q.difficulty===diff));qs.sort((a,b)=>Number(!!state.answers[a.id])-Number(!!state.answers[b.id]));$('#studyList').innerHTML=qs.slice(0,18).map(q=>`<div class="card"><span class="badge">${q.subject}</span><span class="badge">${q.difficulty}</span><h3>${q.topic}</h3><p>${q.q}</p><button class="secondary" onclick="single(${q.id})">Responder</button></div>`).join('')}
function startStudy(){const sub=$('#studySubject').value,topic=$('#studyTopic').value,d=$('#studyDiff').value;let qs=QUESTIONS.filter(q=>(!sub||q.subject===sub)&&(!topic||q.topic===topic)&&(!d||q.difficulty===d));qs=shuffle(qs);qs.sort((a,b)=>Number(!!state.answers[a.id])-Number(!!state.answers[b.id]));if(!qs.length)return alert('Nenhuma questão encontrada.');quiz={ids:qs.slice(0,20).map(q=>q.id),idx:0,mode:'study'};showQuestion()}
function startTopic(subject,topic){const qs=QUESTIONS.filter(q=>q.subject===subject&&q.topic===topic);quiz={ids:shuffle(qs).slice(0,15).map(q=>q.id),idx:0,mode:'study'};showQuestion()}
function single(id){quiz={ids:[id],idx:0,mode:'study'};showQuestion()}

function lessonList(){
 const out=[]; Object.entries(LESSONS).forEach(([subject,arr])=>arr.forEach(x=>out.push({...x,subject}))); return out;
}
function aulas(){
 const all=lessonList(); const cargo=state.cargo;
 $('#content').innerHTML=`<div class="wrap"><div class="hero"><div><span class="badge">TEORIA + PRÁTICA</span><h2>🎓 Aprenda antes de responder</h2><p>Escolha uma matéria, leia a mini-aula, revise o resumo e só depois vá para as questões.</p></div><button class="action" onclick="go('plano')">Ver meu plano</button></div><div class="toolbar"><select id="lessonSubject"><option value="">Todas as matérias</option>${Object.keys(LESSONS).map(s=>`<option>${s}</option>`).join('')}</select><input id="lessonSearch" class="search" placeholder="Buscar assunto..."></div><div id="lessonGrid" class="lesson-grid"></div></div>`;
 const paint=()=>{const sub=$('#lessonSubject').value,q=($('#lessonSearch').value||'').toLowerCase();const list=all.filter(x=>(!sub||x.subject===sub)&&(!q||`${x.title} ${x.topic} ${x.summary}`.toLowerCase().includes(q)));$('#lessonGrid').innerHTML=list.map((x,i)=>`<article class="lesson-card"><span class="badge">${icon(x.subject)} ${x.subject}</span><h3>${x.title}</h3><p>${x.summary}</p><div class="lesson-tags"><span>📌 ${x.topic}</span><span>⚡ ${x.steps.length} pontos</span>${state.studyPlan[x.subject+'|'+x.topic]?.last?'<span>✅ estudado</span>':''}</div><button class="secondary" onclick="openLesson('${escapeAttr(x.subject)}','${escapeAttr(x.topic)}')">Estudar agora</button></article>`).join('')||'<div class="card empty">Nenhuma aula encontrada.</div>';};
 $('#lessonSubject').onchange=paint;$('#lessonSearch').oninput=paint;paint();
}
function openLesson(subject,topic){
 const x=(LESSONS[subject]||[]).find(a=>a.topic===topic);if(!x)return;
 $('#content').innerHTML=`<div class="wrap"><button class="secondary" onclick="go('aulas')">← Voltar para aulas</button><div class="lesson-detail card"><span class="badge">${icon(subject)} ${subject}</span><h2>${x.title}</h2><p class="lead">${x.summary}</p><h3>🧭 Como estudar</h3><ol>${x.steps.map(s=>`<li>${s}</li>`).join('')}</ol><div class="example-box"><b>💡 Exemplo</b><p>${x.example}</p></div><div class="trap-box"><b>⚠️ Pegadinha comum</b><p>${x.trap}</p></div><h3>🧠 Flashcards</h3><div class="flash-grid">${x.flash.map((f,i)=>`<button class="flash" onclick="this.classList.toggle('revealed')"><span>Cartão ${i+1}</span><b>${f}</b></button>`).join('')}</div>${x.source?`<p class="source"><b>Fonte oficial para aprofundamento:</b> <a href="${x.source}" target="_blank" rel="noopener">consultar fonte</a></p>`:''}<div class="lesson-actions"><button class="action" onclick="startTopic('${escapeAttr(subject)}','${escapeAttr(topic)}')">Praticar questões</button><button class="secondary" onclick="markLesson('${escapeAttr(subject)}','${escapeAttr(topic)}')">Marcar como estudado</button></div></div></div>`;
}
function markLesson(subject,topic){const k=subject+'|'+topic;state.studyPlan[k]={...(state.studyPlan[k]||{}),last:new Date().toISOString()};save();toast('✅ Assunto marcado como estudado.');}
function plano(){
 const todayN=Object.values(state.answers).filter(x=>dayOf(x.at)===today()).length; const all=lessonList();
 const scores={}; all.forEach(x=>{const qs=QUESTIONS.filter(q=>q.subject===x.subject&&q.topic===x.topic),a=qs.map(q=>state.answers[q.id]).filter(Boolean),wrong=a.filter(r=>!r.correct).length; scores[x.subject+'|'+x.topic]={answered:a.length,wrong,score:a.length?wrong/a.length:0};});
 const priority=all.map(x=>({...x,...scores[x.subject+'|'+x.topic]})).sort((a,b)=>b.score-a.score||a.answered-b.answered).slice(0,6);
 const cargo=state.cargo; const cargoLessons=all.filter(x=>x.subject===cargo).slice(0,5);
 $('#content').innerHTML=`<div class="wrap"><div class="hero"><div><span class="badge">PLANO ADAPTATIVO</span><h2>🗓️ O que estudar hoje?</h2><p>O plano prioriza assuntos com erros, depois conteúdos ainda não praticados e alterna teoria e questões.</p></div><button class="action" onclick="startDailySession()">Começar sessão</button></div><div class="grid"><div class="card"><div class="muted">Meta diária</div><div class="stat">${Math.min(todayN,state.dailyGoal)}/${state.dailyGoal}</div><p>questões</p></div><div class="card"><div class="muted">Seu cargo</div><div class="stat" style="font-size:20px">${cargo}</div></div><div class="card"><div class="muted">Assuntos com dados</div><div class="stat">${topicStats().length}</div></div><div class="card"><div class="muted">Aulas disponíveis</div><div class="stat">${all.length}</div></div></div><div class="card"><h2>🔥 Prioridade de hoje</h2>${priority.map((x,i)=>`<div class="plan-row"><div><span class="badge">${i+1}</span><b>${x.topic}</b><small>${x.subject} • ${x.answered?`${x.wrong} erros em ${x.answered}`:'ainda não praticado'}</small></div><div><button class="secondary" onclick="openLesson('${escapeAttr(x.subject)}','${escapeAttr(x.topic)}')">Teoria</button> <button class="secondary" onclick="startTopic('${escapeAttr(x.subject)}','${escapeAttr(x.topic)}')">Questões</button></div></div>`).join('')}</div><div class="card"><h2>📚 Sequência sugerida para ${cargo}</h2><ol class="study-sequence">${cargoLessons.map(x=>`<li><b>${x.title}</b><span>${x.summary}</span></li>`).join('')}</ol></div></div>`;
}
function startDailySession(){const all=lessonList();const candidates=all.filter(x=>x.subject==='Português'||x.subject==='Matemática'||x.subject===state.cargo).sort((a,b)=>{const sa=topicStats().find(z=>z.subject===a.subject&&z.topic===a.topic),sb=topicStats().find(z=>z.subject===b.subject&&z.topic===b.topic);return (sb?.errorRate||0)-(sa?.errorRate||0)});const ids=[];candidates.forEach(x=>{QUESTIONS.filter(q=>q.subject===x.subject&&q.topic===x.topic&&!state.answers[q.id]).slice(0,2).forEach(q=>ids.push(q.id));});let rest=QUESTIONS.filter(q=>!state.answers[q.id]&&(q.subject==='Português'||q.subject==='Matemática'||q.subject===state.cargo));rest=shuffle(rest);rest.forEach(q=>{if(ids.length<20&&!ids.includes(q.id))ids.push(q.id)});quiz={ids:ids.slice(0,20),idx:0,mode:'study'};showQuestion();}

function simulado(){
 const cargo=state.cargo;
 $('#content').innerHTML=`<div class="wrap"><div class="grid two"><div class="card"><span class="badge">PROVA DA PREFEITURA</span><h2>🏛️ Simulado por edital</h2><p>Modelo padrão: <b>50 questões</b> — 15 Português + 15 Matemática + 20 Conhecimentos Específicos de <b>${cargo}</b>.</p><div class="grid two"><div><label>Questões</label><select id="prefN"><option>20</option><option>30</option><option selected>50</option></select></div><div><label>Tempo</label><select id="prefTime"><option>30</option><option>45</option><option selected>60</option><option>90</option></select></div></div><button class="action" onclick="startPrefeitura()">Iniciar prova</button></div><div class="card"><span class="badge">TREINO LIVRE</span><h2>🧪 Simulado personalizado</h2><p>Escolha quantidade, dificuldade e matérias para um treino rápido.</p><div class="grid two"><div><label>Questões</label><select id="simN"><option>10</option><option>20</option><option>30</option><option>40</option><option>50</option></select></div><div><label>Tempo</label><select id="simTime"><option>15</option><option selected>30</option><option>45</option><option>60</option><option>90</option></select></div></div><button class="action" onclick="startSim()">Treino livre</button></div></div><div class="card" style="margin-bottom:15px"><span class="badge">POR ASSUNTO</span><h2>🎯 Simulado por tópico</h2><p>Treine um assunto específico com tempo e gabarito comentado.</p><div class="grid two"><div><label>Matéria</label><select id="tsSub" onchange="fillSimTopics()">${subjects().map(x=>`<option>${x}</option>`).join('')}</select></div><div><label>Tópico</label><select id="tsTopic"></select></div></div><div class="grid two"><div><label>Questões</label><select id="tsN"><option>5</option><option selected>10</option><option>15</option></select></div></div><button class="action" onclick="startTopicSim()">Iniciar simulado do tópico</button></div><div class="card"><h3>📌 Como funciona a prova da prefeitura</h3><p>O sistema seleciona questões das matérias comuns e do cargo, controla o tempo, registra a prova separadamente e ao final aponta os tópicos com maior número de erros.</p><p class="muted">Banco atual: ${QUESTIONS.length} questões.</p></div></div>`;
 fillSimTopics();
}
function fillSimTopics(){const s=$('#tsSub').value,el=$('#tsTopic');const ts=(EDITAL[s]||[]).filter(t=>QUESTIONS.some(q=>q.subject===s&&q.topic===t));el.innerHTML=ts.map(t=>`<option value="${escapeAttr(t)}">${t} (${QUESTIONS.filter(q=>q.subject===s&&q.topic===t).length})</option>`).join('')}
function startTopicSim(){const s=$('#tsSub').value,t=$('#tsTopic').value,qs=QUESTIONS.filter(q=>q.subject===s&&q.topic===t);if(!qs.length)return toast('Sem questões neste tópico.');const n=Math.min(Number($('#tsN').value),qs.length);quiz={ids:shuffle(qs).slice(0,n).map(q=>q.id),idx:0,mode:'sim',seconds:Math.max(5,Math.ceil(n*1.5))*60,sessionAnswers:{}};beginTimer();showQuestion()}
function showGabarito(){if(!lastResult)return go('simulado');const L=lastResult;$('#content').innerHTML=`<div class="wrap"><button class="secondary" onclick="go('simulado')">← Voltar</button><h2 style="margin:15px 0">📝 Gabarito comentado</h2>${L.ids.map((id,i)=>{const q=QMAP.get(id),r=L.ans[id];const st=!r?'⚪ Não respondida':r.correct?'✅ Acertou':'❌ Errou';return `<div class="card" style="margin-bottom:12px"><span class="badge">${i+1} · ${q.topic}</span><b>${st}</b><p><b>${q.q}</b></p>${r&&!r.correct?`<p>Sua resposta: ${q.a[r.choice]}</p>`:''}<p>Resposta certa: <b>${q.a[q.correct]}</b></p><p class="muted">${q.explain}</p></div>`}).join('')}</div>`}
function takeRandom(arr,n){return shuffle(arr).slice(0,n)}
function startPrefeitura(){const n=Number($('#prefN').value),mins=Number($('#prefTime').value),specific=QUESTIONS.filter(q=>q.subject===state.cargo);let p=Math.round(n*.30),m=Math.round(n*.30),e=n-p-m;if(n===50){p=15;m=15;e=20} if(specific.length<e)return alert('Não há questões específicas suficientes para esta prova.');const qs=[...takeRandom(QUESTIONS.filter(q=>q.subject==='Português'),p),...takeRandom(QUESTIONS.filter(q=>q.subject==='Matemática'),m),...takeRandom(specific,e)];quiz={ids:qs.sort(()=>Math.random()-.5).map(q=>q.id),idx:0,mode:'prefeitura',seconds:mins*60,sessionAnswers:{}};beginTimer();showQuestion()}
function startSim(){let n=Number($('#simN').value);const mins=Number($('#simTime').value);let qs=takeRandom(QUESTIONS,n);quiz={ids:qs.map(q=>q.id),idx:0,mode:'sim',seconds:mins*60,sessionAnswers:{}};beginTimer();showQuestion()}
function beginTimer(){clearInterval(timer);timer=setInterval(()=>{if(!quiz)return;quiz.seconds--;const el=$('#timer');if(el)el.textContent=fmt(quiz.seconds);if(quiz.seconds<=0){clearInterval(timer);finishQuiz(true)}},1000)}
function fmt(s){return `${String(Math.max(0,Math.floor(s/60))).padStart(2,'0')}:${String(Math.max(0,s%60)).padStart(2,'0')}`}
function showQuestion(){
 if(!quiz||!quiz.ids.length){quiz=null;return toast('Ainda não há questões disponíveis para este assunto.')}
 quiz.sessionAnswers=quiz.sessionAnswers||{};const q=QMAP.get(quiz.ids[quiz.idx]);const answered=quiz.sessionAnswers[q.id];
 $('#content').innerHTML=`<div class="wrap"><div class="question card"><div class="qhead"><span>${quiz.idx+1} de ${quiz.ids.length} · ${q.subject} · ${q.topic}</span><span>${quiz.mode!=='study'?`⏱️ <b id="timer">${fmt(quiz.seconds)}</b>`:`${q.difficulty}`}</span></div><div class="progress"><i style="width:${quiz.idx/quiz.ids.length*100}%"></i></div><div class="qtext">${q.q}</div><div class="answers">${perm(q).map((o,i)=>`<button class="answer ${answered?(o===q.correct?'correct':o===answered.choice?'wrong':''):''}" ${answered?'disabled':''} onclick="answer(${q.id},${o})">${String.fromCharCode(65+i)}) ${q.a[o]}</button>`).join('')}</div>${answered?`<div class="result"><b>${answered.correct?'✅ Resposta correta!':'❌ Resposta incorreta.'}</b><p>${q.explain}</p><button class="action" onclick="nextQ()">${quiz.idx+1<quiz.ids.length?'Próxima':'Finalizar'}</button></div>`:''}</div></div>`;
}
function answer(id,choice){
 const q=QMAP.get(id);const ok=choice===q.correct;const rec={choice,correct:ok,at:new Date().toISOString()};
 const gain=state.answers[id]?.correct?0:(ok?10:2);const prev=state.srs[id];if(!ok)state.srs[id]={box:0,due:addDays(SRS_DAYS[0])};else if(prev&&prev.due<=today()){const b=prev.box+1;if(b>=SRS_DAYS.length)delete state.srs[id];else state.srs[id]={box:b,due:addDays(SRS_DAYS[b])}}quiz.sessionAnswers[id]=rec;state.answers[id]=rec;state.xp+=gain;
 state.attempts.push({id,choice,correct:ok,at:rec.at,mode:quiz.mode});save();showQuestion();
}
function nextQ(){if(quiz.idx+1<quiz.ids.length){quiz.idx++;showQuestion()}else finishQuiz(false)}
function finishQuiz(timeout){
 clearInterval(timer);const ids=quiz.ids,results=ids.map(id=>(quiz.sessionAnswers||{})[id]).filter(Boolean),correct=results.filter(x=>x.correct).length,pct=results.length?Math.round(correct/results.length*100):0;const examMode=quiz.mode!=='study';
 if(examMode){const topics={};ids.forEach(id=>{const q=QMAP.get(id),r=quiz.sessionAnswers[id];if(!r)return;const k=q.subject+'|'+q.topic;if(!topics[k])topics[k]={subject:q.subject,topic:q.topic,total:0,wrong:0};topics[k].total++;if(!r.correct)topics[k].wrong++});state.examHistory.push({date:new Date().toISOString(),mode:quiz.mode,cargo:state.cargo,total:ids.length,answered:results.length,correct,pct,timeout,topics:Object.values(topics)});save();}
 lastResult={ids:[...ids],ans:{...(quiz.sessionAnswers||{})}};quiz=null;const weak=examMode?(state.examHistory.at(-1).topics||[]).filter(x=>x.wrong).sort((a,b)=>b.wrong-a.wrong).slice(0,5):weakTopics(5);
 $('#content').innerHTML=`<div class="wrap"><div class="card empty"><div class="stat">${pct}%</div><h2>${timeout?'⏰ Tempo encerrado':'🏆 Prova concluída!'}</h2><p><b>${correct}</b> acertos de ${results.length} respondidas (${ids.length} no total).</p><p>${examMode?'A prova foi salva no seu histórico.':'Seu progresso foi atualizado.'}</p><h3>🔎 O que revisar</h3><div class="cards">${weak.length?weak.map(w=>`<div class="card"><b>${w.topic}</b><p>${w.wrong} erro(s)</p></div>`).join(''):'<div class="card">Nenhum ponto fraco identificado nesta sessão.</div>'}</div><br><button class="action" onclick="showGabarito()">Ver gabarito comentado</button> <button class="secondary" onclick="go('revisao')">Abrir revisão inteligente</button> <button class="secondary" onclick="go('ranking')">Meu ranking</button></div></div>`;
}
function edital(){const cargo=state.cargo;const topics=EDITAL[cargo]||[];$('#content').innerHTML=`<div class="wrap"><div class="card"><div class="toolbar"><div><span class="badge">EDITAL</span><h2>${icon(cargo)} ${cargo}</h2></div><select onchange="changeCargo(this.value)">${['Agente Comunitário de Saúde','Orientador Social'].map(c=>`<option ${c===cargo?'selected':''}>${c}</option>`).join('')}</select></div><p>Os tópicos abaixo são usados pelo motor de questões e pela revisão inteligente.</p></div><h2>📚 Conteúdo programático</h2><div class="topic-grid">${topics.map(t=>{const qs=QUESTIONS.filter(q=>q.subject===cargo&&q.topic===t),a=qs.filter(q=>state.answers[q.id]),c=a.filter(q=>q.correct);return `<div class="topic"><b>${t}</b><span>${a.length?`${a.length} respondidas • ${Math.round(c.length/a.length*100)}%`:'Ainda não praticado'}</span><button class="secondary" onclick="startTopic('${escapeAttr(cargo)}','${escapeAttr(t)}')">Treinar</button></div>`}).join('')}</div><h2 style="margin-top:25px">📌 Atribuições do cargo</h2><div class="card"><ol>${(ATRIBUICOES[cargo]||[]).map(x=>`<li>${x}</li>`).join('')}</ol></div></div>`}
function review(){
 const weak=weakTopics(12),wrong=QUESTIONS.filter(q=>state.answers[q.id]&&!state.answers[q.id].correct);
 $('#content').innerHTML=`<div class="wrap"><div class="hero"><div><span class="badge">MOTOR ADAPTATIVO</span><h2>🔄 Revisão inteligente</h2><p>O sistema cruza seus erros por assunto e prioriza o que precisa de mais prática.</p></div><button class="action" onclick="reviewAll()">Revisar tudo</button></div>${srsCard()}<h2>🔥 Pontos fracos</h2><div class="cards">${weak.length?weak.map(w=>`<div class="card"><span class="badge">${w.subject}</span><h3>${w.topic}</h3><p>${w.wrong} erro(s) / ${w.total} tentativas</p><div class="progress"><i style="width:${w.errorRate}%"></i></div><small>${w.errorRate}% de erros</small><br><button class="secondary" onclick="startTopic('${escapeAttr(w.subject)}','${escapeAttr(w.topic)}')">Treinar tópico</button></div>`).join(''):'<div class="card empty">Ainda não há dados suficientes para criar uma revisão.</div>'}</div><h2 style="margin-top:25px">❌ Questões erradas</h2><div class="cards">${wrong.length?wrong.slice(0,30).map(q=>`<div class="card"><span class="badge">${q.subject}</span><h3>${q.topic}</h3><p>${q.q}</p><button class="secondary" onclick="single(${q.id})">Refazer</button></div>`).join(''):'<div class="card empty">🎉 Nenhuma questão errada registrada.</div>'}</div></div>`;
}
function reviewAll(){const ids=QUESTIONS.filter(q=>state.answers[q.id]&&!state.answers[q.id].correct).sort((a,b)=>{const aa=state.answers[a.id],bb=state.answers[b.id];return new Date(aa.at)-new Date(bb.at)}).map(q=>q.id);if(!ids.length)return alert('Você ainda não tem questões erradas.');quiz={ids:ids.slice(0,30),idx:0,mode:'study'};showQuestion()}
function statistics(){const subs=subjects();const s=stats(),weak=weakTopics(8);$('#content').innerHTML=`<div class="wrap"><div class="grid"><div class="card"><div class="muted">Total respondido</div><div class="stat">${s.total}</div></div><div class="card"><div class="muted">Acertos</div><div class="stat">${s.correct}</div></div><div class="card"><div class="muted">Aproveitamento</div><div class="stat">${s.pct}%</div></div><div class="card"><div class="muted">XP</div><div class="stat">${state.xp}</div></div></div><div class="card"><h2>📊 Por matéria</h2><table class="table"><thead><tr><th>Matéria</th><th>Respondidas</th><th>Acertos</th><th>Aproveitamento</th></tr></thead><tbody>${subs.map(su=>{const z=subjectStats(su);return `<tr><td>${icon(su)} ${su}</td><td>${z.answered}/${z.total}</td><td>${z.correct}</td><td><div class="bar"><i style="width:${z.pct}%"></i></div>${z.pct}%</td></tr>`}).join('')}</tbody></table></div><div class="card" style="margin-top:15px"><h2>⚠️ Assuntos que mais precisam de atenção</h2>${weak.length?weak.map(w=>`<div class="topic"><b>${w.subject} — ${w.topic}</b><span>${w.wrong} erros em ${w.total} tentativas • ${w.errorRate}% de erros</span></div>`).join(''):'<p>Responda mais questões para gerar a análise.</p>'}</div></div>`}
function ranking(){const h=[...state.examHistory].sort((a,b)=>b.pct-a.pct);const best=h[0],avg=h.length?Math.round(h.reduce((s,x)=>s+x.pct,0)/h.length):0;$('#content').innerHTML=`<div class="wrap"><div class="hero"><div><span class="badge">RANKING PESSOAL</span><h2>🏆 Seu desempenho</h2><p>Não é ranking de outras pessoas: é seu histórico para acompanhar sua evolução.</p></div><button class="action" onclick="go('simulado')">Nova prova</button></div><div class="grid"><div class="card"><div class="muted">Provas realizadas</div><div class="stat">${h.length}</div></div><div class="card"><div class="muted">Melhor nota</div><div class="stat">${best?best.pct:0}%</div></div><div class="card"><div class="muted">Média das provas</div><div class="stat">${avg}%</div></div><div class="card"><div class="muted">Nível</div><div class="stat">${level()}</div></div></div><div class="card"><h2>📈 Histórico</h2>${h.length?`<table class="table"><thead><tr><th>Data</th><th>Modelo</th><th>Cargo</th><th>Resultado</th></tr></thead><tbody>${h.slice(0,20).map(x=>`<tr><td>${new Date(x.date).toLocaleDateString('pt-BR')}</td><td>${x.mode==='prefeitura'?'Prefeitura':'Livre'}</td><td>${x.cargo}</td><td><b>${x.pct}%</b> — ${x.correct}/${x.total}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Faça sua primeira prova para começar seu histórico.</div>'}</div></div>`}
function go(p){clearInterval(timer);currentPage=p;quiz=null;render()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));
$('#themeBtn').onclick=()=>{state.dark=!state.dark;save();render()};
$('#resetBtn').onclick=()=>{if(confirm('Apagar todo o progresso, XP, tentativas e histórico?')){state=fresh();save();render()}};
$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');
$('#exportBtn').onclick=()=>{const b=new Blob([JSON.stringify({app:'central-estudos',version:1,exportedAt:new Date().toISOString(),state},null,1)],{type:'application/json'});const l=document.createElement('a');l.href=URL.createObjectURL(b);l.download='central-estudos-progresso-'+today()+'.json';document.body.appendChild(l);l.click();l.remove();setTimeout(()=>URL.revokeObjectURL(l.href),1500);toast('💾 Progresso exportado.')};
$('#importBtn').onclick=()=>$('#importFile').click();
$('#importFile').onchange=e=>{const f=e.target.files[0];e.target.value='';if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result),st=d.state||d;if(!st||typeof st.answers!=='object'||Array.isArray(st.answers))throw 0;if(!confirm('Substituir o progresso atual pelo arquivo importado?'))return;state={...DEFAULT,...st,answers:st.answers||{},attempts:Array.isArray(st.attempts)?st.attempts:[],examHistory:Array.isArray(st.examHistory)?st.examHistory:[],studyPlan:st.studyPlan||{},flashSeen:st.flashSeen||{},srs:st.srs||{}};migrateSrs(state);save();render();toast('📥 Progresso importado.')}catch(x){toast('Arquivo inválido.')}};r.readAsText(f)};
render();
