const EDITAL = {
  'Português': ['Ortografia','Acentuação gráfica','Pontuação','Classes de palavras','Flexão nominal','Concordância nominal','Flexão verbal','Concordância verbal','Formação de palavras','Estrutura da oração','Coordenação e subordinação','Regência nominal e verbal','Colocação pronominal','Sinonímia','Antônimos','Polissemia','Denotação e conotação','Recursos linguísticos','Redação','Interpretação de textos'],
  'Matemática': ['Propriedades','Simplificação de radicais','Operações com radicais','Racionalização','Equações incompletas','Equações de 1º grau','Equações de 2º grau','Sistemas de equações','Problemas','Relação e função','Função de 1º grau','Função constante','Domínio e imagem','Razão e proporção','Grandezas proporcionais','Regra de três simples','Regra de três composta','Porcentagem','Juros simples','Juros compostos','Números inteiros','Números racionais','Expressões algébricas'],
  'Agente Comunitário de Saúde': ['Princípios e diretrizes do SUS','Vigilância epidemiológica','Doenças transmissíveis','Visita domiciliar','Trabalho de grupo','Testes imunológicos','Notificação de doenças transmissíveis','Diagnóstico de saúde da comunidade','Orientação à comunidade','Avaliação das visitas domiciliares','Epidemiologia','Intoxicação por agrotóxicos','Saúde do escolar','Vacinação','Higiene e alimentação','Entrevista e visita domiciliar','Cadastramento familiar e territorial','Prevenção e controle da malária e dengue'],
  'Orientador Social': ['PNAS','SUAS','Estatuto do Idoso','Política Nacional de Integração da Pessoa com Deficiência','Plano Nacional de Enfrentamento ao Abuso Sexual e Exploração Sexual de Crianças e Adolescentes','ECA – Lei nº 8.069/1990','CRAS','Trabalho social com famílias','Atribuições do Orientador Social','Abordagem social e busca ativa','Oficinas e atividades coletivas','Rede socioassistencial','Garantia de direitos','Fortalecimento de vínculos']
};
const ATRIBUICOES = {
 'Agente Comunitário de Saúde': [
 'Integrar equipe de saúde e população da área acompanhada.', 'Trabalhar com registro de famílias em base geográfica definida: a microárea.', 'Manter contato com famílias e desenvolver ações educativas de promoção da saúde e prevenção.', 'Cadastrar as pessoas da microárea e manter os cadastros atualizados.', 'Orientar famílias sobre a utilização dos serviços de saúde disponíveis.', 'Desenvolver promoção da saúde, prevenção, vigilância e visitas domiciliares.', 'Acompanhar famílias e indivíduos sob sua responsabilidade por visitas domiciliares.', 'Atuar na prevenção e controle da malária e da dengue conforme legislação e regulamentos.', 'Orientar e encaminhar famílias para consultas, exames e atendimentos quando necessário.', 'Atuar em áreas prioritárias da atenção básica.', 'Manter a equipe informada sobre a situação das famílias, especialmente as em risco.', 'Desenvolver educação e vigilância à saúde.', 'Promover educação e mobilização comunitária para saneamento e melhoria do meio ambiente.', 'Traduzir para a equipe a dinâmica social, necessidades, potencialidades e limites da comunidade.', 'Identificar parceiros e recursos existentes na comunidade.', 'Executar demais determinações compatíveis com a área de atuação.'
 ],
 'Orientador Social': [
 'Desenvolver atividades socioeducativas, de convivência e socialização voltadas à proteção e garantia de direitos.', 'Contribuir para o fortalecimento da função protetiva da família.', 'Desenvolver atividades e registros para assegurar direitos, autonomia, autoestima, convívio e participação social.', 'Assegurar a participação social dos usuários nas etapas do trabalho social.', 'Apoiar abordagem social e busca ativa.', 'Atuar na recepção dos usuários, proporcionando ambiência acolhedora.', 'Apoiar identificação e registro de necessidades, assegurando privacidade das informações.', 'Apoiar e participar do planejamento das ações.', 'Organizar e facilitar oficinas e atividades individuais e coletivas.', 'Acompanhar, orientar e monitorar usuários na execução das atividades.', 'Apoiar eventos artísticos, lúdicos e culturais.', 'Apoiar campanhas e mobilizações intersetoriais para prevenção e enfrentamento de riscos e violações de direitos.', 'Apoiar registros das atividades e subsidiar a equipe de referência.', 'Apoiar orientação, informação, encaminhamentos e acesso a serviços, programas, projetos e benefícios.', 'Apoiar acompanhamento dos encaminhamentos realizados.', 'Articular-se com a rede socioassistencial e políticas públicas.', 'Participar das reuniões de equipe para planejamento e avaliação.', 'Contribuir para prevenção de rompimentos de vínculos familiares e comunitários.', 'Apoiar identificação e acompanhamento de famílias em descumprimento de condicionalidades.', 'Informar e encaminhar usuários para cursos, qualificação profissional e inclusão produtiva.', 'Acompanhar ingresso, frequência e desempenho dos usuários em cursos por meio de registros.', 'Apoiar desenvolvimento de mapas de oportunidades e demandas.', 'Participar de reuniões, encontros, seminários e treinamentos quando convocado.', 'Realizar atividades administrativas junto ao Conselho Tutelar e Conselhos dos Direitos da Criança e do Adolescente.', 'Executar outras tarefas compatíveis solicitadas pela chefia imediata.'
 ]
};
