const LESSONS={
'Português':[
{topic:'Interpretação de textos',title:'Como interpretar sem cair em pegadinhas',summary:'Leia para identificar assunto, tese, finalidade, informações explícitas e inferências autorizadas pelo texto.',steps:['Leia o comando antes de marcar a alternativa.','Separe o que o texto afirma do que a alternativa apenas sugere.','Procure palavras absolutas como “sempre”, “nunca” e “somente”.','Em questões de inferência, escolha apenas o que pode ser sustentado pelo texto.'],example:'Se o texto afirma que “alguns moradores participaram”, não é possível concluir que todos participaram.',trap:'Confundir conhecimento pessoal com informação fornecida pelo texto.',flash:['Explícito = está escrito.','Inferência = conclusão permitida pelo texto.','Tema = assunto central.']},
{topic:'Acentuação gráfica',title:'Acentuação: descubra a sílaba tônica primeiro',summary:'A classificação em oxítona, paroxítona e proparoxítona orienta boa parte das regras de acentuação.',steps:['Separe mentalmente a palavra em sílabas.','Identifique a sílaba tônica.','Verifique a regra correspondente.','Revise casos de hiato e ditongos quando aplicável.'],example:'“Lâmpada” é proparoxítona; palavras proparoxítonas são acentuadas.',trap:'Decorar listas sem entender a posição da sílaba tônica.',flash:['Oxítona: última sílaba tônica.','Paroxítona: penúltima.','Proparoxítona: antepenúltima.']},
{topic:'Pontuação',title:'Pontuação e sentido',summary:'Pontuação organiza a estrutura da frase e pode alterar o sentido ou destacar relações sintáticas.',steps:['Identifique sujeito e predicado antes de separar termos.','Use vírgulas para elementos deslocados, explicativos e enumerações conforme a estrutura.','Não separe sujeito de predicado por vírgula sem justificativa sintática.'],example:'“Maria, a diretora, chegou.” A expressão entre vírgulas explica quem é Maria.',trap:'Usar vírgula apenas porque existe uma pausa na fala.',flash:['Pontuação é sintaxe + sentido.','Nem toda pausa oral vira vírgula.']},
{topic:'Classes de palavras',title:'Reconhecendo a função das palavras',summary:'Artigo, nome/substantivo, pronome, verbo, preposição e conjunção têm funções diferentes na frase.',steps:['Veja a palavra dentro da frase, não isoladamente.','Pergunte qual relação ela estabelece.','Observe flexões de gênero, número, pessoa e tempo quando existirem.'],example:'Em “O aluno estudou”, “o” é artigo, “aluno” é substantivo e “estudou” é verbo.',trap:'Classificar uma palavra fora do contexto.',flash:['Artigo acompanha o substantivo.','Pronome pode substituir ou acompanhar o nome.','Verbo expressa ação, estado ou fenômeno.']},
{topic:'Concordância verbal',title:'Quem concorda com o verbo?',summary:'O verbo normalmente concorda com o núcleo do sujeito segundo pessoa e número.',steps:['Encontre o verbo.','Pergunte quem pratica/sofre a ação ou apresenta o estado.','Localize o núcleo do sujeito.','Faça a concordância com esse núcleo.'],example:'“Os candidatos estudam.” O núcleo “candidatos” está no plural, então o verbo fica no plural.',trap:'Concordar com a palavra mais próxima do verbo em vez do núcleo do sujeito.',flash:['Ache o núcleo do sujeito.','Depois ajuste o verbo.']},
{topic:'Regência nominal e verbal',title:'Quem exige qual preposição?',summary:'Regência estuda a relação de dependência entre termos e as preposições exigidas por nomes ou verbos.',steps:['Identifique o termo regente.','Verifique se ele exige preposição.','Observe o complemento e o sentido produzido.'],example:'“Assistir ao filme” no sentido de ver exige a preposição “a” na norma-padrão.',trap:'Escolher preposição apenas pelo costume da fala.',flash:['Regente = termo que exige.','Regido = termo dependente.']},
{topic:'Colocação pronominal',title:'Próclise, mesóclise e ênclise',summary:'A posição do pronome oblíquo depende da estrutura da oração e de palavras atrativas.',steps:['Procure elementos atrativos, como palavras negativas e certos pronomes/conjunções.','Verifique se a norma e o contexto favorecem próclise, ênclise ou mesóclise.'],example:'“Não me disseram a verdade.” A palavra negativa favorece a próclise.',trap:'Aplicar uma única posição do pronome a todas as frases.',flash:['Próclise = pronome antes do verbo.','Ênclise = depois.','Mesóclise = no meio do verbo.']},
{topic:'Sinonímia',title:'Relações de sentido',summary:'Sinonímia aproxima sentidos; antonímia estabelece oposição; polissemia ocorre quando uma palavra apresenta sentidos relacionados conforme o contexto.',steps:['Analise o contexto.','Substitua mentalmente a palavra.','Veja se o sentido é preservado, invertido ou modificado.'],example:'“Banco” pode designar instituição financeira ou assento: o contexto determina o sentido.',trap:'Tratar sinônimo como palavra necessariamente idêntica em todos os contextos.',flash:['Sinônimo ≠ igualdade absoluta.','Polissemia depende do contexto.']},
{topic:'Denotação e conotação',title:'Sentido literal e figurado',summary:'Denotação tende ao sentido literal; conotação usa sentidos associados ou figurados.',steps:['Pergunte se a expressão está sendo usada literalmente.','Procure metáfora, comparação, ironia e outras figuras quando o contexto indicar.'],example:'“Ele tem um coração de pedra” usa sentido figurado para caracterizar alguém como insensível.',trap:'Interpretar toda expressão figurada literalmente.',flash:['Denotativo = literal.','Conotativo = figurado/contextual.']},
{topic:'Redação',title:'Estrutura de uma resposta escrita',summary:'Uma redação clara precisa de organização, coerência, coesão, adequação ao tema e domínio da norma solicitada.',steps:['Entenda exatamente o tema.','Planeje começo, desenvolvimento e fechamento.','Use conectivos para ligar ideias.','Revise concordância, pontuação e repetição de palavras.'],example:'Antes de escrever, faça um mini-esquema com tese, dois argumentos e conclusão.',trap:'Começar a escrever sem definir o que será defendido.',flash:['Tema → planejamento → desenvolvimento → revisão.']}
],
'Matemática':[
{topic:'Razão e proporção',title:'Razão, proporção e comparação',summary:'Razão compara grandezas por divisão; proporção estabelece igualdade entre duas razões.',steps:['Identifique as grandezas e suas unidades.','Monte a razão na mesma ordem nos dois lados.','Use multiplicação cruzada quando houver proporção.'],example:'2/5 = x/20 → 5x=40 → x=8.',trap:'Inverter uma razão sem inverter a outra.',flash:['Razão = comparação.','Proporção = igualdade entre razões.']},
{topic:'Regra de três simples',title:'Regra de três sem decorar cruzamentos',summary:'Use a regra de três quando duas grandezas mantêm relação proporcional direta ou inversa.',steps:['Monte a tabela.','Decida se a relação é direta ou inversa.','Só depois faça o cálculo.','Confira se o resultado faz sentido.'],example:'Se 3 cadernos custam R$ 18, 5 cadernos custam R$ 30, mantendo o preço unitário.',trap:'Usar regra de três sem verificar se as grandezas são proporcionais.',flash:['Direta: aumenta/aumenta ou diminui/diminui.','Inversa: aumenta/diminui.']},
{topic:'Porcentagem',title:'Porcentagem como fração de 100',summary:'Percentual é uma razão com base 100. Transforme a taxa em decimal ou fração para calcular.',steps:['20% = 20/100 = 0,20.','Parte = total × taxa.','Em aumentos, some a variação ao valor inicial; em descontos, subtraia.'],example:'20% de 350 = 350 × 0,20 = 70.',trap:'Achar que aumento de 20% seguido de desconto de 20% volta ao valor original.',flash:['p% = p/100.','Valor final depende da ordem das operações.']},
{topic:'Juros simples',title:'Juros simples',summary:'No regime simples, os juros são calculados sobre o capital inicial.',steps:['Identifique capital (C), taxa (i) e tempo (t).','Use J=C·i·t.','Monte o montante M=C+J.','Converta a taxa e o tempo para unidades compatíveis.'],example:'C=1000, i=2% ao mês, t=3 meses → J=60 e M=1060.',trap:'Usar taxa mensal com tempo em anos sem conversão.',flash:['J=C·i·t.','M=C+J.']},
{topic:'Juros compostos',title:'Juros compostos',summary:'No regime composto, cada período incorpora os juros ao saldo para o cálculo seguinte.',steps:['Use M=C(1+i)^t.','Converta a taxa para decimal.','Calcule a potência conforme o número de períodos.'],example:'C=1000, i=10%, t=2 → M=1000×1,1²=1210.',trap:'Somar os juros de cada período como se fossem simples.',flash:['Composto: juros sobre juros.','M=C(1+i)^t.']},
{topic:'Equações de 1º grau',title:'Isolando a incógnita',summary:'Uma equação de primeiro grau pode ser resolvida mantendo a igualdade e realizando operações equivalentes nos dois lados.',steps:['Elimine parênteses e reduza termos semelhantes.','Reúna os termos com x de um lado.','Isole x.','Confira substituindo o resultado na equação.'],example:'2x+6=18 → 2x=12 → x=6.',trap:'Mudar um termo de lado sem compreender que a operação inversa é aplicada.',flash:['Equação = igualdade.','Sempre confira o resultado.']},
{topic:'Equações de 2º grau',title:'Bhaskara e análise da equação',summary:'Na forma ax²+bx+c=0, o discriminante Δ=b²−4ac ajuda a determinar as raízes reais.',steps:['Coloque a equação na forma padrão.','Identifique a, b e c.','Calcule Δ.','Use x=(-b±√Δ)/(2a).'],example:'x²−5x+6=0 → Δ=1 → raízes 2 e 3.',trap:'Errar o sinal de b ou c ao calcular o discriminante.',flash:['Δ=b²−4ac.','Δ<0 não possui raízes reais.']},
{topic:'Função de 1º grau',title:'Função afim',summary:'Uma função de primeiro grau pode ser escrita como f(x)=ax+b. O coeficiente a determina a inclinação e b o valor inicial.',steps:['Identifique a e b.','Para um x dado, substitua na expressão.','Observe se a é positivo ou negativo para saber o comportamento.'],example:'f(x)=2x+3 → f(4)=11.',trap:'Confundir o coeficiente angular com o termo independente.',flash:['f(x)=ax+b.','a>0: crescente; a<0: decrescente.']},
{topic:'Operações com radicais',title:'Simplificação e operações com radicais',summary:'Radicais podem ser simplificados retirando fatores que formam potências perfeitas.',steps:['Fatore o radicando.','Separe quadrados/cubos perfeitos conforme o índice.','Só some radicais semelhantes após simplificação.'],example:'√72=√(36×2)=6√2.',trap:'Somar radicandos diretamente: √2+√3 ≠ √5.',flash:['Simplifique antes de operar.','Radicais semelhantes têm mesma parte radical.']},
{topic:'Sistemas de equações',title:'Duas incógnitas, duas relações',summary:'Sistemas simples podem ser resolvidos por substituição ou eliminação.',steps:['Escolha a equação mais fácil de isolar.','Substitua na outra ou elimine uma incógnita.','Encontre a segunda variável.','Confira nas duas equações.'],example:'x+y=10 e x−y=2 → 2x=12 → x=6, y=4.',trap:'Parar depois de descobrir apenas uma incógnita.',flash:['Sistema exige solução que satisfaça todas as equações.']}
],
'Agente Comunitário de Saúde':[
{topic:'Princípios e diretrizes do SUS',title:'SUS: princípios que mais caem',summary:'Estude os princípios e diretrizes do SUS relacionando-os a situações concretas de atendimento e organização do sistema.',steps:['Associe universalidade ao acesso.','Associe integralidade ao cuidado articulado e contínuo.','Revise descentralização, participação da comunidade e organização regionalizada/hierarquizada conforme o conteúdo legal.'],example:'Uma questão pode apresentar uma situação de acesso ao serviço e perguntar qual princípio está relacionado.',trap:'Confundir princípio com uma atribuição específica do ACS.',flash:['Universalidade = acesso.','Integralidade = cuidado articulado.','Participação da comunidade = controle social.'],source:'https://planalto.gov.br/ccivil_03/leis/l8080.htm'},
{topic:'Visita domiciliar',title:'Visita domiciliar do ACS',summary:'A visita domiciliar integra o acompanhamento territorial e o vínculo com famílias e comunidade.',steps:['Conheça o território e a família.','Observe situações relevantes para a saúde.','Oriente dentro de suas competências.','Registre informações necessárias e comunique a equipe quando houver situação que demande acompanhamento.'],example:'A visita pode ajudar a identificar necessidades e fortalecer o vínculo entre usuário, família e equipe.',trap:'Confundir orientação do ACS com diagnóstico ou prescrição médica.',flash:['Visita = vínculo + acompanhamento + educação em saúde.'],source:'https://www.gov.br/saude/pt-br/composicao/saps/esf/equipe-saude-da-familia/faq/qual-e-o-papel-do-agente-comunitario-de-saude'},
{topic:'Cadastramento familiar e territorial',title:'Território, microárea e cadastro',summary:'O conhecimento do território permite organizar o acompanhamento das famílias e identificar necessidades.',steps:['Delimite a área de atuação.','Mantenha registros atualizados.','Identifique situações de risco e vulnerabilidade.','Compartilhe informações relevantes com a equipe conforme os fluxos de trabalho.'],example:'Mudança de endereço ou composição familiar pode exigir atualização cadastral.',trap:'Tratar cadastro como atividade isolada, sem relação com o planejamento territorial.',flash:['Território orienta o planejamento.','Cadastro precisa ser atualizado.']},
{topic:'Vigilância epidemiológica',title:'Vigilância: observar, comunicar e agir',summary:'A vigilância epidemiológica envolve informações que subsidiam medidas de prevenção e controle de doenças e agravos.',steps:['Reconheça eventos relevantes.','Observe padrões no território.','Siga os fluxos de comunicação/notificação aplicáveis.','Apoie ações educativas e de prevenção.'],example:'A identificação de aumento de casos pode exigir comunicação à equipe e ações de controle.',trap:'Achar que vigilância significa apenas registrar casos depois que o problema terminou.',flash:['Informação → análise → prevenção/controle.']},
{topic:'Vacinação',title:'Como estudar vacinação para a prova',summary:'Calendários e normas podem ser atualizados. Para a prova, estude o calendário oficial vigente e entenda conceitos como indicação, faixa etária, esquema e registro.',steps:['Consulte sempre a fonte oficial mais recente.','Separe vacina, dose, faixa etária e situação especial.','Treine interpretação de esquemas em vez de decorar uma tabela isolada.'],example:'Uma questão pode fornecer idade e histórico vacinal e pedir a conduta prevista no calendário vigente.',trap:'Estudar calendário antigo de apostilas sem conferir atualização oficial.',flash:['Calendário vigente > tabela antiga.','Leia idade + histórico + situação.'],source:'https://www.gov.br/saude/pt-br/composicao/svsa/pni/calendario-tecnico/calendario-tecnico'},
{topic:'Doenças transmissíveis',title:'Cadeia de transmissão',summary:'Compreender agente, reservatório, porta de saída, transmissão, porta de entrada e hospedeiro ajuda a raciocinar sobre prevenção.',steps:['Identifique como a doença é transmitida.','Relacione a transmissão às medidas preventivas.','Associe ações de higiene, vacinação, controle de vetores e isolamento quando indicados.'],example:'Se a transmissão depende de vetor, medidas de controle devem considerar o ambiente e o vetor.',trap:'Memorizar a doença sem entender a via de transmissão.',flash:['Conheça a via de transmissão para entender a prevenção.']},
{topic:'Intoxicação por agrotóxicos',title:'Reconhecimento e prevenção',summary:'No território rural, prevenção inclui orientação sobre exposição, armazenamento, uso adequado e busca de atendimento diante de sinais de intoxicação.',steps:['Identifique possíveis situações de exposição.','Oriente medidas preventivas dentro das competências.','Em caso de suspeita, siga os fluxos de atendimento e comunicação do serviço de saúde.'],example:'A exposição pode ocorrer durante aplicação, armazenamento ou contato com roupas e equipamentos contaminados.',trap:'Tratar sintomas graves em casa sem procurar atendimento.',flash:['Prevenção + reconhecimento da exposição + encaminhamento adequado.']},
{topic:'Higiene e alimentação',title:'Educação em saúde no cotidiano',summary:'Orientações simples sobre água, alimentos, higiene das mãos, armazenamento e hábitos saudáveis podem prevenir agravos.',steps:['Identifique o risco concreto.','Oriente de forma compreensível.','Considere as condições reais da família e do território.','Acompanhe quando necessário.'],example:'A orientação deve ser adaptada às condições de acesso à água, alimentos e serviços.',trap:'Dar orientação genérica sem considerar a realidade da família.',flash:['Educação em saúde precisa ser compreensível e contextualizada.']}
],
'Orientador Social':[
{topic:'PNAS',title:'Proteção Social na PNAS',summary:'Estude a lógica da política de assistência social: proteção social, vulnerabilidades, riscos, direitos e organização dos serviços.',steps:['Diferencie vulnerabilidade de violação de direitos.','Relacione proteção social básica à prevenção de riscos e fortalecimento de vínculos.','Relacione proteção especial a situações que demandam atenção especializada.'],example:'Uma família em vulnerabilidade pode acessar serviços da proteção básica para prevenção de agravamentos.',trap:'Reduzir assistência social a concessão de benefícios financeiros.',flash:['Assistência social é política pública de proteção social e garantia de direitos.']},
{topic:'SUAS',title:'Como enxergar o SUAS',summary:'O SUAS organiza a assistência social em rede, articulando serviços, benefícios, programas, projetos e unidades.',steps:['Entenda a lógica de proteção básica e especial.','Relacione unidade, serviço, público e objetivo.','Pense sempre em rede e território.'],example:'A unidade não deve ser estudada isoladamente do serviço que oferta.',trap:'Confundir CRAS e CREAS ou misturar seus objetivos.',flash:['SUAS = sistema organizado de proteção social.']},
{topic:'CRAS',title:'CRAS: porta de entrada da Assistência Social',summary:'O CRAS é uma unidade pública da assistência social voltada prioritariamente à proteção social básica e ao trabalho territorial.',steps:['Associe CRAS à proteção social básica.','Relacione CRAS ao PAIF e ao SCFV.','Pense no território, prevenção e fortalecimento de vínculos.'],example:'Uma família em vulnerabilidade pode buscar o CRAS para orientação e acesso a serviços e benefícios.',trap:'Tratar o CRAS como unidade exclusivamente para situações de violação de direitos.',flash:['CRAS → proteção básica.','PAIF → trabalho social com famílias.'],source:'https://www.gov.br/mds/pt-br/acoes-e-programas/suas/unidades-de-atendimento/centro-de-referencia-de-assistencia-social-cras'},
{topic:'Trabalho social com famílias',title:'PAIF e trabalho social com famílias',summary:'O PAIF apoia famílias, previne rupturas de vínculos, promove acesso a direitos e desenvolve ações no território.',steps:['Entenda a família como sujeito de direitos.','Use escuta, orientação, acompanhamento e encaminhamento quando cabíveis.','Relacione trabalho individual, coletivo e territorial.'],example:'Uma visita domiciliar pode integrar o acompanhamento, quando adequada ao trabalho social.',trap:'Confundir acompanhamento com controle ou fiscalização da família.',flash:['PAIF = trabalho social com famílias no CRAS.'],source:'https://www.gov.br/mds/pt-br/acoes-e-programas/suas/servicos-e-programas/protecao-e-atencao-integral-a-familia'},
{topic:'Atribuições do Orientador Social',title:'O que o Orientador Social faz',summary:'As atribuições do edital enfatizam atividades socioeducativas, convivência, participação, oficinas, registros, mobilização, encaminhamentos e apoio à equipe.',steps:['Relacione atividade ao objetivo socioeducativo.','Registre o trabalho realizado.','Respeite privacidade e direitos dos usuários.','Articule com a equipe e a rede conforme o fluxo institucional.'],example:'Organizar uma oficina de convivência exige planejamento, acolhimento, participação e registro.',trap:'Assumir atribuições privativas de outras profissões ou agir fora dos fluxos institucionais.',flash:['Socioeducativo + convivência + direitos + trabalho em equipe.']},
{topic:'Abordagem social e busca ativa',title:'Busca ativa não é espera passiva',summary:'Busca ativa envolve identificar pessoas e famílias que podem estar fora do acesso aos serviços e aproximá-las da rede.',steps:['Conheça o território.','Identifique sinais de desproteção.','Faça contato respeitoso.','Oriente e encaminhe conforme as necessidades e os fluxos.'],example:'A busca ativa pode localizar famílias em territórios de difícil acesso ou pessoas que ainda não chegaram aos serviços.',trap:'Confundir busca ativa com exposição pública ou constrangimento.',flash:['Busca ativa = aproximar a proteção social de quem está fora do acesso.']},
{topic:'Rede socioassistencial',title:'Trabalhar em rede',summary:'A atuação socioassistencial depende de articulação entre serviços, políticas públicas e órgãos de garantia de direitos.',steps:['Identifique a necessidade.','Descubra qual serviço ou política tem competência para atendê-la.','Faça encaminhamento adequado.','Acompanhe o fluxo conforme atribuição e orientação da equipe.'],example:'Uma demanda pode envolver assistência social, saúde, educação e órgãos de defesa de direitos.',trap:'Encaminhar sem registrar ou sem compreender a finalidade do serviço de destino.',flash:['Rede = articulação, não simples lista de contatos.']}
]};
